apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata: 
  name: issuer 
spec:
  acme: 
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: "safiaaddow@gmail.com"
    privateKeySecretRef:
      name: issuer
    solvers: 
    - dns01:
        route53:
          hostedZoneID: Z002259024GMXMVUFXH2A
          region: eu-west-2
      selector:
        dnsZones: 
        - "lab.safiaaddow.uk"
    - http01:
        ingress:
          class: nginx


